language: ruby
rvm:
- 2.2.5

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
    ./script/cibuild &&
    ./script/test

after_success:
        ./script/deploy

# branch whitelist, only for GitHub Pages
branches:
  only:
  - Multisite-update

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - ENCRYPTION_LABEL: "52cc44cf4ef0"
  - COMMIT_AUTHOR_EMAIL: "mike.trebilcock@cornwall.ac.uk"

sudo: false # route your build to the container-based infrastructure for a faster build