sudo: required
dist: trusty
group: deprecated-2017Q4

language: ruby
rvm:
- 2.5.0


before_install:
  - sudo apt-get install git ruby ruby-dev zlib1g-dev curl build-essential -y
  - curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh
  - sudo bash nodesource_setup.sh
  - sudo apt-get install nodejs
  - sudo npm install --global gulp

before_script:
  - npm install -g gulp
  - npm install

script: gulp deploy && script/deploy

git:
  depth: 3

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - ENCRYPTION_LABEL: "52cc44cf4ef0"
  - COMMIT_AUTHOR_EMAIL: "ashley.uterhark@cornwall.ac.uk"

#sudo: false # route your build to the container-based infrastructure for a faster build
