language: ruby
rvm:
- 2.2.5


before_install:
  - nvm install 4.2

before_script:
  - npm install -g gulp
  - npm install

script: gulp deploy && script/deploy

git:
  depth: 3
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - ENCRYPTION_LABEL: "52cc44cf4ef0"
  - COMMIT_AUTHOR_EMAIL: "mike.trebilcock@duchy.ac.uk"

sudo: false # route your build to the container-based infrastructure for a faster build
