# Site settings
title: The Career College | The Cornwall College Group
email: webmaster@cornwall.ac.uk
author: The Cornwall College Group
baseurl: "" # the subpath of your site, e.g. /blog/

collections:
  campaign:
    output: true

# Build settings
markdown: kramdown
# Do not copy these files to the output directory
exclude:
  - vendor
  - SupportCode
  - README.md
  - CornwallCollegeTravisBot
  - CornwallCollegeTravisBot.enc
  - Gemfile
  - Gemfile.lock
  - win_build.cmd
  - script
  - html-minifier.conf
  - node_modules
  - gulpconfig.json
  - gulpfile.js
  - package.json

gems:
    - jekyll-assets

assets:
    cache: false
    sources:
        - _assets/js
        - _assets/css
        - css

sitemap:
    exclude: 
        - "/CNAME"
        - "/sitemap-index.xml"


relative_permalinks: false

schema-college: "http://schema.org/CollegeOrUniversity"

cornwall-base-url: "https://www.cornwall.ac.uk/"
duchy-base-url: "https://www.duchy.ac.uk/"
bicton-base-url: "https://www.bicton.ac.uk/"
falmouth-base-url: "https://www.falmouthmarineschool.ac.uk/"