# Site settings
title: The Career College | The Cornwall College Group
email: webmaster@cornwall.ac.uk
author: Cornwall College
description: "Cornwall College offers a range of subjects through a variety of qualifications including: A-levels, Diplomas, NVQs, Apprenticeships and Degree courses."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://m.cornwall.ac.uk" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
course_site_baseurl: http://network.cornwall.ac.uk/

# Build settings
markdown: kramdown
exclude:
  - [vendor]
  - SupportCode
  
gems:
   - closure-compiler

# Plugins.
asset_bundler:
  bundle_name: mini-v8.43

  compress:
    js: false
    css: false

relative_permalinks: false