#!/usr/bin/env bash
if [ "$TRAVIS_BRANCH" == "master" ]; then
    set -e # halt script on error
    export JEKYLL_ENV="production"
    echo "PRODUCTION BUILD"
fi

if [ "$TRAVIS_BRANCH" != "master" ]; then
    export JEKYLL_ENV="test"
    echo "DEVELOPMENT BUILD"
fi

echo "BUILD - Start Bicton"
bundle exec jekyll build --config _config.yml,_site_bicton_ac_uk.yml

echo "BUILD - Start Cornwall"
bundle exec jekyll build --config _config.yml,_site_cornwall_ac_uk.yml

echo "BUILD - Start Duchy"
bundle exec jekyll build --config _config.yml,_site_duchy_ac_uk.yml

echo "BUILD - Start Falmouth"
bundle exec jekyll build --config _config.yml,_site_falmouthmarineschool_ac_uk.yml

if [ "$TRAVIS_BRANCH" == "master" ]; then
	echo =========================
	echo GZIP All Html, css and js
	echo =========================

	find _site/ -iname '*.html' -exec gzip -n {} +
	find _site/ -iname '*.js' -exec gzip -n {} +
	find _site/ -iname '*.css' -exec gzip -n {} +
	find _site/ -iname '*.gz' -exec rename 's/\.gz$//i' {} +
	echo done.   
fi