#!/usr/bin/env bash
set -e # halt script on error

bundle install
bundle exec jekyll build --config _config.yml,_site_duchy_ac_uk.yml
bundle exec jekyll build --config _config.yml,_site_cornwall_ac_uk.yml
bundle exec jekyll build --config _config.yml,_site_bicton_ac_uk.yml
bundle exec jekyll build --config _config.yml,_site_falmouthmarineschool_ac_uk.yml
