#!/usr/bin/env bash
set -e # halt script on error
bundle exec jekyll build --config _config.yml,_site_bicton_ac_uk.yml
bundle exec jekyll build --config _config.yml,_site_cornwall_ac_uk.yml
bundle exec jekyll build --config _config.yml,_site_duchy_ac_uk.yml
bundle exec jekyll build --config _config.yml,_site_falmouthmarineschool_ac_uk.yml

bundle exec htmlproofer ./_site/bicton_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/bicton_ac_uk/error.txt 2>&1
bundle exec htmlproofer ./_site/cornwall_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/cornwall_ac_uk/error.txt 2>&1
bundle exec htmlproofer ./_site/duchy_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/duchy_ac_uk/error.txt 2>&1
bundle exec htmlproofer ./_site/falmouthmarineschool_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/falmouthmarineschool_ac_uk/error.txt 2>&1
