#!/usr/bin/env bash

bundle exec htmlproofer ./_site/bicton_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/bicton_ac_uk/error.txt 2>&1
bundle exec htmlproofer ./_site/cornwall_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/cornwall_ac_uk/error.txt 2>&1
bundle exec htmlproofer ./_site/duchy_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/duchy_ac_uk/error.txt 2>&1
bundle exec htmlproofer ./_site/falmouthmarineschool_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/falmouthmarineschool_ac_uk/error.txt 2>&1